### ISSUE TITLE
UX: satellite.earth displaying reports/blocks on profiles without clear indication

### ISSUE THREAD

**Issue by mrusme** [lovvtide/satellite-web#25]
This is a UX issue, but imho a very bad one. Assuming a profile would go around an Block/Report posts on Nostr, satellite (and hence satellite.earth) displays all these posts on that accounts profile page. The only indication about the post being a Block/Report event is a tiny yellow exclamation-mark icon next to the profile name, that uninvolved users might not even know the meaning of.

This leads to basically a timeline full of harmful (blocked/reported) content for an account, making it appear as if that account had anything to do with the content.

Imho this is a design flaw and should be corrected. Block/report events should not be listed as part of a profile's public timeline. It could be part of a dedicated tab that is ideally not visible to anonymous users browsing satellite.earth (or any other installation for that purpose).

**Comment by lovvtide** [comment]
Can you give me a link to an example of what you're talking about? Satellite does not display block requests on the profile feed.

**Comment by mrusme** [comment]
@lovvtide scroll down on [my profile](https://satellite.earth/@npub1ntvtt70k4r3y8tc0qmszwae68xn8l9df3j3phcdccrchdslwn7psqpx9ss) to ~22 days ago and you will see -- very prominently -- a post/account that I have reported/blocked. The only indication given is the following icon:

![screenshot_2024-02-05-123231](https://github.com/lovvtide/satellite-web/assets/151967/9893fd85-12a0-47f3-8035-f4a4c5af0766)

However, as there is no text, nor tooltip or basically anything, to uninvolved users this could mean anything and nothing. Given the fact that it is highly problematic content that was reported/blocked, it's very unfortunate how it is being displayed on the profile.

Assuming I would continue blocking/reporting such content I'm truly frightened of what my public profile on satellite would look like.

**Comment by lovvtide** [comment]
Ok I found the source of the problem. Satellite pulls kind 7 reaction events to show posts that you've reacted to, and whatever client you used to report that post incorrectly created a kind 7 reaction event with "⚠️" as the content instead of following [the spec](https://github.com/nostr-protocol/nips/blob/master/56.md) and creating a kind 1984 reporting event.

See for yourself:
https://njump.me/nevent1qqsqultpsz7rk2hvp35xjww4ec229zu6hpj8xrqd6dm6eulwvqm2wkgprpmhxue69uhhyetvv9ujumn0wdmksetjv5hxxmmdqyt8wumn8ghj7un9d3shjtnwdaehgu3wvfskueqzyzdd3d0e765wysa0purwqfmh8gu6vlu44xx2yxlphrq0zakra60cxggj8ur

If you remember which client you used to create this reporting event I would notify the developer so they can fix this asap.

**Comment by mrusme** [comment]
@lovvtide thank you kindly for the insightful explanation, appreciate it!

I *believe* that it was Amethyst. I quickly checked the source code and it seems like [it does indeed have the event type](https://github.com/vitorpamplona/amethyst/blob/5cd3096221ce40a18f3fdbfc259d2d11adace896/quartz/src/main/java/com/vitorpamplona/quartz/events/ReactionEvent.kt#L50) you mentioned, including the warning emoji. I just don't know exactly how its being triggered, as Amethyst does implement [1984](https://github.com/vitorpamplona/amethyst/blob/5cd3096221ce40a18f3fdbfc259d2d11adace896/quartz/src/main/java/com/vitorpamplona/quartz/events/ReportEvent.kt#L81) as well.

I cannot remember 100%, but I believe I tapped the vertical "..." on the post, tapped *Block/Report* and then used the "Post Report" button. I'm assuming that this is what triggered event `7`. Maybe @vitorpamplona could quickly validate if this makes sense.

In any case, it is very unfortunate that the *end result* looks like this. I quickly checked how it looks [on Iris](https://iris.to/npub1ntvtt70k4r3y8tc0qmszwae68xn8l9df3j3phcdccrchdslwn7psqpx9ss) and there the event doesn't seem to appear on the profile page at all. Same on [nostter](https://nostter.app/npub1ntvtt70k4r3y8tc0qmszwae68xn8l9df3j3phcdccrchdslwn7psqpx9ss). Same on [Coracle](https://coracle.social/people/npub1ntvtt70k4r3y8tc0qmszwae68xn8l9df3j3phcdccrchdslwn7psqpx9ss). Same on [Primal](https://primal.net/p/npub1ntvtt70k4r3y8tc0qmszwae68xn8l9df3j3phcdccrchdslwn7psqpx9ss).

I'm not perfectly familiar with the individual NIPs, but it seems like these sort of events are generally not displayed as prominently as Satellite seems to do it. On the other hand, Amethyst appears to be a little too unclear with "⚠️".

As I'm not that deeply involved in the protocol I cannot tell what the solution to this is. However, the way it is right now appears less than ideal. Maybe someone more knowledgeable can clarify things here?

Thanks!

**Comment by vitorpamplona** [comment]
`⚠️` was the old version of reports before the report NIP-56 was even considered. For a long time, Amethyst used to create both the `⚠️` and the report kind to make sure Clients that did not support NIP-56 at least received a bad reaction from our users. We haven't created `⚠️` since last September, but Amethyst still assigns a negative value when it sees that emoji.

**Comment by mrusme** [comment]
That was fast; Thank you @vitorpamplona! Since I'm using the F-Droid release it's possible that I've been using an older version of Amethyst, as releases there usually take a bit of time.

From what I understand this was basically a feature that existed before an official specification came along, and every client can interpret it the way they see fit.

As this hopefully won't happen in future to anyone that updated to a newer Amethyst version, it begs the question on whether Satellite should follow the *convention* and at least not display the content as prominently on people's profile pages, or whether that's too much effort to be implemented. @lovvtide feel free to leave this issue open or close it, depending on how you decide to proceed.

As for me, I'm going to try to [delete](https://nostr-delete.vercel.app/) that particular event, as it throws an odd light unfortunately.

**Comment by lovvtide** [comment]
I just pushed a fix:
https://github.com/lovvtide/satellite-web/commit/95bd168d34392c6acf7a621a70898881c001a8b8

Should be good to go 👍

**Comment by mrusme** [comment]
@lovvtide you are awesome, thank you! I can confirm that I cannot see the event on the public profile on satellite.earth any longer.

**Comment by lovvtide** [comment]
Np mate
