### ISSUE TITLE
NIP-09 support?

### ISSUE THREAD

**Issue by verityj** [lovvtide/satellite-web#3]
Sure, it's optional for relays to respect a deletion event. But a delete request button on Satellite would be great. Simple "Delete" next to my note. 

Thanks for all your great work so far!

**Comment by lovvtide** [comment]
Satellite does already support delete. It's the trashcan icon just below each of your notes.

**Comment by verityj** [comment]
Oh, I see it now! Sorry, I completely missed it.

<img width="145" alt="Screenshot 2023-06-27 at 13 36 11" src="https://github.com/lovvtide/satellite-web/assets/954902/6286c991-cc93-412c-9c0b-ebad16c4070c">
