### ISSUE TITLE
Get rid of the superfluous "@" in address

### ISSUE THREAD

**Issue by verityj** [lovvtide/satellite-web#4]
I see absolutely no reason to type `https://satellite.earth/@jack@cash.app` instead of just `https://satellite.earth/jack@cash.app`. Why make it more instead of less? Please align with others and keep it simple.

`https://iris.to/jack@cash.app` - they did it right.

Why wouldn't you?

**Comment by lovvtide** [comment]
Thank you for the suggestion. I considered what you're suggesting (the bare pathname) in the original design but decided against it to avoid creating dependence on various heuristics to parse the pathname as an identifier.

**Comment by verityj** [comment]
Thank you for the explanation. I do hope you reconsider and somehow make it happen, right now every website seems to be all over the place in the path design.

To note: If you make any changes, it would be great for me to know. I think you have the most promising layout and so I linked all items on my news sources nostr list to satellite (it's growing to ~100 now): https://verityj.github.io/nostr-news-feeds (work in progress, I am new to Nostr)

**Comment by lovvtide** [comment]
I will certainly keep you apprised. Btw that's a cool site you got there!
