### ISSUE TITLE
Add support to RTL script - Right to Left text

### ISSUE THREAD

**Issue by damascene** [lovvtide/satellite-web#9]
Many languages including Arabic, Persian, Urdu, Uygur and Hebrew are languages that are written from right to left (RTL)

Please add support to post using RTL languages, maybe by using the `direction: rtl` tag in div

More info about RTL: https://rtlcss.com/learn/

**Comment by lovvtide** [comment]
This is something I have on my medium/long-term todo list. I wish it was as simple as adding a css tag but unfortunately it will require significant work to make this work because Satellite has a complex layout with a lot of margins/padding/transforms that will need to be manually refactored.

**Comment by damascene** [comment]
could you please keep the issue open so it will be more visible and someone might contribute a PR for it?
